apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
        - name: quiz-app
          image: manora/quiz-app:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/quiz-db"
            - name: PORT
              value: "3000"