apiVersion: v1
kind: Service
metadata:
  name: quiz-app-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: quiz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000